# Третье упражнение

## Пункт первый

Загрузите в датафрейм JSON-файл, созданный в предыдущем упражнении.
Установите столбец CarNumber в качестве индекса.

In [1]:
import pandas as pd

df = pd.read_json("data/auto.json")
df = df.set_index("CarNumber")

## Пункт второй

Отобразите строки, где штрафы больше 2 100.
Отобразите строки, где штрафы больше 2 100, а возврат (Refund) равен 2.
Отобразите строки, где модель входит в список: ['Focus', 'Corolla'].
Отобразите строки, где номер автомобиля входит в список:
['Y7689C197RUS', '92928M178RUS', '7788KT197RUS', 'H115YO163RUS', 'X758HY197RUS'].

In [2]:
df[df["Fines"] > 2100] # Штрафы больше 2100

              Refund         Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.000000        Ford    Focus
E432XX77RUS        1   6500.000000      Toyota    Camry
92918M178RUS       1   5700.000000        Ford    Focus
H234YH197RUS       2   6000.000000        Ford    Focus
E40577152RUS       1   8594.586466        Ford    Focus
...              ...           ...         ...      ...
O718MM163RUS       2   8594.586466        Ford    Focus
7065C8197RUS       2  11400.000000  Volkswagen   Passat
O22097197RUS       1  24300.000000        Ford    Focus
M0309X197RUS       1  22300.000000        Ford    Focus
H419XE197RUS       2   8594.586466      Toyota  Corolla

[455 rows x 4 columns]

In [3]:
df[(df["Fines"] > 2100) & (df["Refund"] == 2)]

              Refund         Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.000000        Ford    Focus
H234YH197RUS       2   6000.000000        Ford    Focus
707987163RUS       2   2200.000000        Ford    Focus
K330T8197RUS       2   8200.000000       Skoda  Octavia
M592CH197RUS       2   8594.586466       Skoda  Octavia
...              ...           ...         ...      ...
O136HO197RUS       2   7800.000000      Toyota  Corolla
O68897197RUS       2  12300.000000        Ford    Focus
O718MM163RUS       2   8594.586466        Ford    Focus
7065C8197RUS       2  11400.000000  Volkswagen   Passat
H419XE197RUS       2   8594.586466      Toyota  Corolla

[309 rows x 4 columns]

In [4]:
sort_list = ['Focus', 'Corolla']
df[df["Model"].isin(sort_list)]

              Refund         Fines    Make    Model
CarNumber
Y163O8161RUS       2   3200.000000    Ford    Focus
7184TT36RUS        1   2100.000000    Ford    Focus
X582HE161RUS       2   2000.000000    Ford    Focus
92918M178RUS       1   5700.000000    Ford    Focus
H234YH197RUS       2   6000.000000    Ford    Focus
...              ...           ...     ...      ...
Y163O8161RUS       2   1600.000000    Ford    Focus
M0309X197RUS       1  22300.000000    Ford    Focus
O673E8197RUS       2    600.000000    Ford    Focus
8610T8154RUS       1   2000.000000    Ford    Focus
H419XE197RUS       2   8594.586466  Toyota  Corolla

[593 rows x 4 columns]

In [5]:
number_list = ['Y7689C197RUS', '92928M178RUS', '7788KT197RUS', 'H115YO163RUS', 'X758HY197RUS']
df[df.index.isin(number_list)]

              Refund          Fines  Make  Model
CarNumber
92928M178RUS       1    8594.586466  Ford  Focus
H115YO163RUS       1    2200.000000  Ford  Focus
7788KT197RUS       2   12000.000000  Ford  Focus
X758HY197RUS       2   24200.000000  Ford  Focus
X758HY197RUS       2   72600.000000  Ford  Focus
Y7689C197RUS       1   27000.000000  Ford  Focus
92928M178RUS       1     600.000000  Ford  Focus
H115YO163RUS       1    8594.586466  Ford  Focus
H115YO163RUS       2    1100.000000  Ford  Focus
7788KT197RUS       2    8594.586466  Ford  Focus
7788KT197RUS       1   20000.000000  Ford  Focus
X758HY197RUS       2  145200.000000  Ford  Focus
92928M178RUS       1    1200.000000  Ford  Focus
Y7689C197RUS       2    9000.000000  Ford  Focus
Y7689C197RUS       2   45000.000000  Ford  Focus
7788KT197RUS       2    4000.000000  Ford  Focus
Y7689C197RUS       1   36000.000000  Ford  Focus
92928M178RUS       2    3000.000000  Ford  Focus

## Пункт третий

Выполните агрегации по Make и Model:
Выведите медианные значения штрафов, сгруппировав по Make.
Выведите медианные значения штрафов, сгруппировав по Make и Model.
Выведите количество штрафов, сгруппированное по Make и Model, чтобы понять, можно ли доверять медиане.
Выведите минимальные и максимальные штрафы, сгруппированные по Make и Model, чтобы лучше понять разброс.
Выведите стандартное отклонение штрафов, сгруппированное по Make и Model, чтобы лучше понять разброс.

In [6]:
df.groupby("Make")["Fines"].median()

Make
Audi          4200.0
BMW           6500.0
Ford          3500.0
Skoda         3250.0
Toyota        7700.0
Volkswagen    4300.0
Volvo         8500.0
Name: Fines, dtype: float64

In [7]:
df.groupby(["Make", "Model"])["Fines"].median()

Make        Model
Ford        Focus      3500.0
            Mondeo     7650.0
Skoda       Octavia    3250.0
Toyota      Camry      7700.0
            Corolla    7700.0
Volkswagen  Golf       4800.0
            Jetta      2800.0
            Passat     3500.0
            Touareg    5800.0
Name: Fines, dtype: float64

In [8]:
df.groupby(["Make", "Model"])["Fines"].count() # Количество штрафов, сгруппированное по make и model

Make        Model
Ford        Focus      575
            Mondeo       6
Skoda       Octavia     48
Toyota      Camry       16
            Corolla     18
Volkswagen  Golf        20
            Jetta        6
            Passat      22
            Touareg      5
Name: Fines, dtype: int64

Мы делаем вывод, что медиане однозначно можно доверять в случаях с моделью Focus и Octavia, потому что чем больше значений, тем устойчивее медиана

In [9]:
df.groupby(["Make", "Model"])["Fines"].min()

Make        Model
Ford        Focus       100.0
            Mondeo     1100.0
Skoda       Octavia     300.0
Toyota      Camry       500.0
            Corolla     900.0
Volkswagen  Golf        200.0
            Jetta       500.0
            Passat      100.0
            Touareg     500.0
Name: Fines, dtype: float64

In [10]:
df.groupby(["Make", "Model"])["Fines"].max()

Make        Model
Ford        Focus      180000.000000
            Mondeo      46200.000000
Skoda       Octavia    145000.000000
Toyota      Camry       22400.000000
            Corolla     34300.000000
Volkswagen  Golf       168000.000000
            Jetta       46000.000000
            Passat      29700.000000
            Touareg      8594.586466
Name: Fines, dtype: float64

In [11]:
df.groupby(["Make", "Model"])["Fines"].std()

Make        Model
Ford        Focus      15041.269437
            Mondeo     18987.329108
Skoda       Octavia    24339.742174
Toyota      Camry       6410.250654
            Corolla     9629.325617
Volkswagen  Golf       36950.839950
            Jetta      17743.026799
            Passat      6969.739135
            Touareg     3461.778173
Name: Fines, dtype: float64

## Пункт четвёртый

Выведите номера автомобилей, сгруппированные по количеству штрафов в порядке убывания - хотим найти тех, кто чаще всего нарушал.
Из исходного датафрейма выберите все строки, соответствующие топ-1 номеру - приблизимся и посмотрим детали.
Выведите номера автомобилей, сгруппированные по сумме штрафов в порядке убывания - хотим найти тех, кто заплатил больше всех.
Из исходного датафрейма выберите все строки, соответствующие топ-1 номеру по сумме штрафов.
Постройте таблицу, которая отвечает на вопрос: «Есть ли номера автомобилей, привязанные к разным моделям?»

In [12]:

mf = df.groupby(df.index)["Fines"].count().sort_values(ascending=False)
mf

CarNumber
Y7689C197RUS    4
92928M178RUS    4
7788KT197RUS    4
H115YO163RUS    3
X758HY197RUS    3
               ..
E42577152RUS    1
E42377152RUS    1
E41977152RUS    1
E41577152RUS    1
H917TC36RUS     1
Name: Fines, Length: 531, dtype: int64

In [13]:
#Топ 1 по количеству штрафов
mf = mf.head(1)
s = df.loc[mf.index[0]]
s

              Refund    Fines  Make  Model
CarNumber
Y7689C197RUS       1  27000.0  Ford  Focus
Y7689C197RUS       2   9000.0  Ford  Focus
Y7689C197RUS       2  45000.0  Ford  Focus
Y7689C197RUS       1  36000.0  Ford  Focus

In [14]:
sf = df.groupby(df.index)["Fines"].sum().sort_values(ascending=False)
sf

CarNumber
X758HY197RUS    242000.0
9020YC197RUS    217500.0
M0279X197RUS    216000.0
Y352O8197RUS    207200.0
Y778EE197RUS    192000.0
                  ...
83218C154RUS       100.0
Y195O8161RUS       100.0
K376HE161RUS       100.0
705787163RUS       100.0
K326T8197RUS       100.0
Name: Fines, Length: 531, dtype: float64

In [18]:
#Топ 1 по сумме штрафов
sfi = mf.head(1)
si = df.loc[sfi.index[0]]
si

              Refund    Fines  Make  Model
CarNumber
Y7689C197RUS       1  27000.0  Ford  Focus
Y7689C197RUS       2   9000.0  Ford  Focus
Y7689C197RUS       2  45000.0  Ford  Focus
Y7689C197RUS       1  36000.0  Ford  Focus

In [25]:
#Таблица, которая показывает есть ли разные модели с одинаковым номером
kf = df.groupby(df.index)["Model"].nunique()
kf
kf.max()

np.int64(1)

Если вывод kf.max() = 1, значит разных моделей с одинаковыми номерами нет