# Упражнение 04

## Пункт первый

Прочитай JSON-файл, сохранённый в ex02.
Одна из колонок имеет тип float, задай формат отображения через pd.options.display.float_format: числа с плавающей точкой должны показываться с двумя знаками после запятой.
В столбце Model есть пропущенные значения; ничего с ними не делай.

In [25]:
import pandas as pd
import numpy as np
import requests

ds = pd.read_json("data/auto.json")
pd.options.display.float_format = "{:.2f}".format
ds

        CarNumber  Refund    Fines    Make    Model
0    Y163O8161RUS       2  3200.00    Ford    Focus
1     E432XX77RUS       1  6500.00  Toyota    Camry
2     7184TT36RUS       1  2100.00    Ford    Focus
3    X582HE161RUS       2  2000.00    Ford    Focus
4    92918M178RUS       1  5700.00    Ford    Focus
..            ...     ...      ...     ...      ...
720  Y163O8161RUS       2  1600.00    Ford    Focus
721  M0309X197RUS       1 22300.00    Ford    Focus
722  O673E8197RUS       2   600.00    Ford    Focus
723  8610T8154RUS       1  2000.00    Ford    Focus
724  H419XE197RUS       2  8594.59  Toyota  Corolla

[725 rows x 5 columns]

## Пункт второй

Создай сэмпл из 200 новых наблюдений, используя random_state = 21.
В сэмпле не должно появиться новых комбинаций car number, make и model, чтобы набор данных оставался согласованным.
На столбцы refund и fines ограничений нет: можно случайно выбирать их значения и назначать любому номеру автомобиля.

In [26]:
sample = ds.sample(n=200,random_state=21)
sample

        CarNumber  Refund    Fines        Make   Model
445  M0299X197RUS       2 19200.00        Ford   Focus
22   83298C154RUS       2  8594.59        Ford   Focus
93   H957HY161RUS       1  2000.00        Ford   Focus
173   T941CC96RUS       1  2000.00        Ford   Focus
697  H966HY161RUS       1   500.00        Ford   Focus
..            ...     ...      ...         ...     ...
14   8182XX154RUS       1   200.00        Ford   Focus
623   X796TH96RUS       1   500.00        Ford   Focus
498  T011MY163RUS       2  4000.00        Ford   Focus
536   T341CC96RUS       2  1000.00  Volkswagen  Passat
520   T119CT96RUS       1  2000.00        Ford   Focus

[200 rows x 5 columns]

## Пункт третий

Конкатенируй сэмпл с исходным DataFrame и получи новый DataFrame concat_rows.

In [27]:
concat_rows = pd.concat([ds, sample])
concat_rows

        CarNumber  Refund   Fines        Make   Model
0    Y163O8161RUS       2 3200.00        Ford   Focus
1     E432XX77RUS       1 6500.00      Toyota   Camry
2     7184TT36RUS       1 2100.00        Ford   Focus
3    X582HE161RUS       2 2000.00        Ford   Focus
4    92918M178RUS       1 5700.00        Ford   Focus
..            ...     ...     ...         ...     ...
14   8182XX154RUS       1  200.00        Ford   Focus
623   X796TH96RUS       1  500.00        Ford   Focus
498  T011MY163RUS       2 4000.00        Ford   Focus
536   T341CC96RUS       2 1000.00  Volkswagen  Passat
520   T119CT96RUS       1 2000.00        Ford   Focus

[925 rows x 5 columns]

## Пункт четвертый 

Создай Series с именем Year со случайными целыми числами от 1980 до 2019.
Перед генерацией лет вызови np.random.seed(21).
Конкатенируй Series с DataFrame и назови получившийся DataFrame fines.

In [28]:
np.random.seed(21)

years = pd.Series(np.random.randint(1980,2020, size=len(concat_rows)), name="Year", index=concat_rows.index)
fines = pd.concat([concat_rows, years], axis=1)
fines

        CarNumber  Refund   Fines        Make   Model  Year
0    Y163O8161RUS       2 3200.00        Ford   Focus  1989
1     E432XX77RUS       1 6500.00      Toyota   Camry  1995
2     7184TT36RUS       1 2100.00        Ford   Focus  1984
3    X582HE161RUS       2 2000.00        Ford   Focus  2015
4    92918M178RUS       1 5700.00        Ford   Focus  2014
..            ...     ...     ...         ...     ...   ...
14   8182XX154RUS       1  200.00        Ford   Focus  1981
623   X796TH96RUS       1  500.00        Ford   Focus  1992
498  T011MY163RUS       2 4000.00        Ford   Focus  2007
536   T341CC96RUS       2 1000.00  Volkswagen  Passat  2005
520   T119CT96RUS       1 2000.00        Ford   Focus  1997

[925 rows x 6 columns]

## Пункт пятый

Создай новый DataFrame с номерами автомобилей и их владельцами.
Возьми самые популярные фамилии в США (файл surname.json в папке datasets).
Создай новую Series с фамилиями: без спецсимволов (запятых, скобок и т. п.); количество должно совпадать с числом уникальных номеров автомобилей в сэмпле (используй random_state = 21).
Создай DataFrame owners с колонками CarNumber и SURNAME.

In [29]:
surnames = pd.read_json("data/surname.json")
car_numbers = fines["CarNumber"].drop_duplicates()
selected_surnames = surnames["SURNAME"].sample(n=car_numbers.nunique(), random_state=21).reset_index(drop=True)
owners = pd.DataFrame({
    "CarNumber": car_numbers.reset_index(drop=True),
    "SURNAME":selected_surnames
})
owners

        CarNumber    SURNAME
0    Y163O8161RUS    CAMACHO
1     E432XX77RUS   MCCARTHY
2     7184TT36RUS    RAYMOND
3    X582HE161RUS  MCFARLAND
4    92918M178RUS      POOLE
..            ...        ...
526  O136HO197RUS    SANTANA
527  O22097197RUS     PORTER
528  M0309X197RUS       CHAN
529  O673E8197RUS    CLAYTON
530  8610T8154RUS     BARTON

[531 rows x 2 columns]

## Пункт шестой

Добавь ещё пять наблюдений в fines (придумай свои CarNumber и т. п.).

In [30]:
new_rows = pd.DataFrame({
    "CarNumber": [
        "A001AA77RUS",
        "B002BB77RUS",
        "C003CC77RUS",
        "E004EE77RUS",
        "K005KK77RUS"
    ],
    "Refund": [1, 0, 2, 1, 0],
    "Fines": [1500.0, 2500.0, 500.0, 3000.0, 750.0],
    "Make": ["Toyota", "BMW", "Ford", "Kia", "Hyundai"],
    "Model": ["Camry", "X5", "Focus", "Rio", "Solaris"],
    "Year": [2015, 2018, 2012, 2019, 2017]
})

fines = pd.concat([fines, new_rows], ignore_index=True)
fines.tail()

       CarNumber  Refund   Fines     Make    Model  Year
925  A001AA77RUS       1 1500.00   Toyota    Camry  2015
926  B002BB77RUS       0 2500.00      BMW       X5  2018
927  C003CC77RUS       2  500.00     Ford    Focus  2012
928  E004EE77RUS       1 3000.00      Kia      Rio  2019
929  K005KK77RUS       0  750.00  Hyundai  Solaris  2017

## Пункт седьмой

Удали последние 20 наблюдений из owners и добавь три новых, отличных от добавленных в fines.

In [31]:
owners = owners.iloc[:-5]
new_owners = pd.DataFrame({
    "CarNumber": [
        "M111MM99RUS",
        "P222PP50RUS",
        "T333TT78RUS"
    ],
    "SURNAME": [
        "MILLER",
        "WILSON",
        "ANDERSON"
    ]
})

owners = pd.concat([owners, new_owners], ignore_index=True)
owners.tail()

        CarNumber   SURNAME
524  E53477152RUS   BERNARD
525   7194TT36RUS     CRAIG
526   M111MM99RUS    MILLER
527   P222PP50RUS    WILSON
528   T333TT78RUS  ANDERSON

## Пункт восьмой, соединения таблиц

In [32]:
#1. Только номера, которые есть в обоих DataFrame
both = fines.merge(owners, on="CarNumber", how="inner")

#2. Все номера из обоих DataFrame
all_numbers = fines.merge(owners, on="CarNumber", how="outer")

#3. Все номера из fines
from_fines = fines.merge(owners, on="CarNumber", how="left")

#4. Все номера из owners
from_owners = fines.merge(owners, on="CarNumber", how="right")

## Пункт девятый

Создай сводную таблицу (pivot table) из fines.
https://platform.21-school.ru/services/storage/download/public_any/e09df235-0b5f-4a5a-a541-da43564a9bcb?path=gitlab/content_versions/886517/7e52c64f-e24a-4233-b1b4-bb6badddf518.png

In [33]:
pivot = fines.pivot_table(
    index=["Make", "Model"],
    columns="Year",
    values="Fines",
    aggfunc="sum"
)

pivot

Year                    1980      1981      1982     1983     1984      1985  \
Make       Model
BMW        X5            NaN       NaN       NaN      NaN      NaN       NaN
Ford       Focus   110294.59 408983.76 165883.76 64800.00 96989.17 162683.76
           Mondeo        NaN       NaN       NaN      NaN      NaN       NaN
Hyundai    Solaris       NaN       NaN       NaN      NaN      NaN       NaN
Kia        Rio           NaN       NaN       NaN      NaN      NaN       NaN
Skoda      Octavia   2400.00       NaN   7300.00 11594.59      NaN  10294.59
Toyota     Camry    12000.00   8594.59       NaN  7200.00      NaN       NaN
           Corolla       NaN       NaN   2000.00      NaN      NaN       NaN
Volkswagen Golf     30900.00       NaN       NaN  8594.59   300.00  24000.00
           Jetta         NaN       NaN       NaN      NaN      NaN       NaN
           Passat        NaN   1600.00       NaN  3200.00 10000.00   5000.00
           Touareg       NaN       NaN       NaN      NaN      NaN   5800.00

Year                   1986      1987      1988      1989  ...      2010  \
Make       Model                                           ...
BMW        X5           NaN       NaN       NaN       NaN  ...       NaN
Ford       Focus   96589.17 125700.00 111789.17 176094.59  ... 142678.35
           Mondeo       NaN       NaN       NaN   8600.00  ...       NaN
Hyundai    Solaris      NaN       NaN       NaN       NaN  ...       NaN
Kia        Rio          NaN       NaN       NaN       NaN  ...       NaN
Skoda      Octavia   600.00   5200.00   5200.00  91400.00  ...   3100.00
Toyota     Camry        NaN       NaN       NaN  22400.00  ...       NaN
           Corolla      NaN  14900.00       NaN   4000.00  ...  24000.00
Volkswagen Golf         NaN  44800.00       NaN   5800.00  ...       NaN
           Jetta        NaN       NaN       NaN       NaN  ...       NaN
           Passat  15000.00  12300.00       NaN       NaN  ...   2800.00
           Touareg      NaN       NaN       NaN       NaN  ...   6300.00

Year                    2011     2012      2013      2014      2015     2016  \
Make       Model
BMW        X5            NaN      NaN       NaN       NaN       NaN      NaN
Ford       Focus   103478.35 97600.00 139394.59 122678.35 209100.00 98089.17
           Mondeo        NaN 34400.00       NaN       NaN       NaN 46200.00
Hyundai    Solaris       NaN      NaN       NaN       NaN       NaN      NaN
Kia        Rio           NaN      NaN       NaN       NaN       NaN      NaN
Skoda      Octavia    500.00   500.00  12594.59    300.00  46394.59   300.00
Toyota     Camry         NaN  8594.59       NaN   1000.00   1500.00      NaN
           Corolla   8594.59 30300.00       NaN       NaN       NaN   900.00
Volkswagen Golf       300.00      NaN  20800.00       NaN   2300.00      NaN
           Jetta         NaN      NaN       NaN       NaN       NaN      NaN
           Passat        NaN      NaN       NaN       NaN    600.00  2100.00
           Touareg       NaN      NaN       NaN   1300.00    500.00      NaN

Year                    2017      2018     2019
Make       Model
BMW        X5            NaN   2500.00      NaN
Ford       Focus   263000.00 274089.17 78889.17
           Mondeo        NaN       NaN      NaN
Hyundai    Solaris    750.00       NaN      NaN
Kia        Rio           NaN       NaN  3000.00
Skoda      Octavia   8594.59 156200.00  9500.00
Toyota     Camry         NaN  21594.59 18100.00
           Corolla   9600.00   7600.00      NaN
Volkswagen Golf          NaN   1000.00      NaN
           Jetta         NaN       NaN      NaN
           Passat        NaN       NaN      NaN
           Touareg       NaN       NaN      NaN

[12 rows x 40 columns]

## Пункт десятый

Сохрани оба DataFrame - fines и owners - в CSV-файлы без индекса.

In [34]:
fines.to_csv("data/fines.csv", index=False)

In [35]:
owners.to_csv("data/owners.csv", index=False)